SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Models/Chart/ChartDataset.cs
namespace SmartBatteryTesterWebApp.UI.Models.Chart
{
    public class ChartDataset
    {
        public ChartDataset()
        {
            Data = new List<decimal>();
        }
        public string? Label { get; set; }
        public string? BackgroundColor { get; set; }
        public int BorderWidth { get; set; }
        public string? BorderColor { get; set; }
        public List<decimal> Data { get; set; }
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Models/Chart/ChartJsData.cs
namespace SmartBatteryTesterWebApp.UI.Models.Chart
{
    public class ChartJsData
    {
        public ChartJsData()
        {
            Labels = new List<string>();
            Datasets = new List<ChartDataset>();
        }
        public List<string> Labels { get; set; }
        public List<ChartDataset> Datasets { get; set; }
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Models/MeasurementSetViewModel.cs
namespace SmartBatteryTesterWebApp.UI.Models
{
    public class MeasurementSetViewModel
    {
        public int Id { get; set; }
        public string? MeasurementName { get; set; }
        public string? MeasurementStatus { get; set; }
        public TimeSpan? DischargeDuration { get; set; }
        public decimal? ResultCapacity { get; set; }
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Models/MeasurementViewModel.cs
namespace SmartBatteryTesterWebApp.UI.Models
{
    public class MeasurementViewModel
    {
        public decimal Voltage { get; set; }
        public decimal Current { get; set; }
        public string? MeasurementDateTime { get; set; }
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartBatteryTesterWebApp.UI.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index() => View();
    
        public IActionResult Error() => View();
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Controllers/HistoryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SmartBatteryTesterWebApp.BLL.DTO;
using SmartBatteryTesterWebApp.BLL.Interfaces;
using SmartBatteryTesterWebApp.UI.Infrastructure;
using SmartBatteryTesterWebApp.UI.Models;

namespace SmartBatteryTesterWebApp.UI.Controllers
{
    public class HistoryController : Controller
    {
        IMeasurementOutputService _measurementService;
        IMeasurementChartDataCreator _chartCreator;

        public HistoryController(IMeasurementOutputService measurementService, IMeasurementChartDataCreator chartCreator)
        {
            _measurementService = measurementService;
            _chartCreator = chartCreator;
        }

        [HttpGet]
        public async Task<IActionResult> IndexAsync(int measurementSetNumber)
        {
            IMapper mapper;
            List<MeasurementSetDTO> measurementSetDTOs = await _measurementService.GetMeasurementSetAsync();
            mapper = new MapperConfiguration(m => m.CreateMap<MeasurementSetDTO, MeasurementSetViewModel>()).CreateMapper();
            var measurementSets = mapper.Map<List<MeasurementSetDTO>, List<MeasurementSetViewModel>>(measurementSetDTOs);
            ViewBag.MeasurementSetList = new SelectList(measurementSets, "Id", "MeasurementName");

            if (measurementSetNumber == 0)
            {
                ViewBag.MeasurementResults = null;
            }
            else
            {
                ViewBag.MeasurementResults = measurementSets.Where(m => m.Id == measurementSetNumber).FirstOrDefault();

                List<MeasurementDTO> measurementDTOs = await _measurementService.GetMeasurementAsync(measurementSetNumber);
                mapper = new MapperConfiguration(m => m.CreateMap<MeasurementDTO, MeasurementViewModel>()).CreateMapper();
                var measurements = mapper.Map<List<MeasurementDTO>, List<MeasurementViewModel>>(measurementDTOs);

                ViewBag.ChartData = _chartCreator.GetLineChartData(measurements);
            }

            return View();
        }
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Controllers/MeasurementController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SmartBatteryTesterWebApp.BLL.DTO;
using SmartBatteryTesterWebApp.BLL.Interfaces;
using SmartBatteryTesterWebApp.UI.Infrastructure;
using SmartBatteryTesterWebApp.UI.Models;
using SmartBatteryTesterWebApp.UI.Models.Chart;

namespace SmartBatteryTesterWebApp.UI.Controllers
{
    public class MeasurementController : Controller
    {
        IMeasurementOutputService _measurementService;
        IMeasurementChartDataCreator _chartCreator;

        public MeasurementController(IMeasurementOutputService measurementService, IMeasurementChartDataCreator chartCreator)
        {
            _measurementService = measurementService;
            _chartCreator = chartCreator;
        }

        public async Task<IActionResult> IndexAsync()
        {
            IMapper mapper;
            ChartJsData chartData;

            var measurementSetDTO = await _measurementService.FindMeasurementSetAsync("Батарея разряжается");
            mapper = new MapperConfiguration(m => m.CreateMap<MeasurementSetDTO, MeasurementSetViewModel>()).CreateMapper();
            var measurementSet = mapper.Map<MeasurementSetDTO, MeasurementSetViewModel>(measurementSetDTO);

            if (measurementSet == null) 
            {
                chartData = _chartCreator.GetLineChartData(new List<MeasurementViewModel>());
            }
            else
            {
                List<MeasurementDTO> measurementDTOs = await _measurementService.GetMeasurementAsync(measurementSet.Id);
                mapper = new MapperConfiguration(m => m.CreateMap<MeasurementDTO, MeasurementViewModel>()).CreateMapper();
                var measurements = mapper.Map<List<MeasurementDTO>, List<MeasurementViewModel>>(measurementDTOs);
                chartData = _chartCreator.GetLineChartData(measurements);
            }

            return View(chartData);
        }
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/ViewComponents/MeasurementsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SmartBatteryTesterWebApp.UI.Models.Chart;

namespace SmartBatteryTesterWebApp.UI.ViewComponents
{
    public class MeasurementsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ChartJsData chartJs)
        {
            return View("MeasurementsChart", chartJs);
        }
    }
}

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Views/About/Index.cshtml
@{
    ViewData["Title"] = "О проекте";
}

<div class="text-center">
    <h3>О проекте</h3>
</div>

<div>
    <div class="border-start border-5 mt-4"">
        <div class="about_title">
            <div class="about_title_description">
                Описание
            </div>
        </div>
        <div class="text-start ms-3">
            <p>Данный ресурс предназначен для удаленного контроля процесса разряда аккумуляторных батарей.</p>
            <p>Проект состоит из веб-приложения, приложения для Windows и устройства на микроконтроллере ATmega8A (MCU).</p>
            <p>
                MCU измеряет напряжение АКБ и отправляет измеренные значения Windows-приложению.
                Для передачи данных MCU использует внутренний приемо-передатчик USART, подключение к ПК осуществляется через 
                преобразователь USB-TTL. Подключение и отключение разрядного устройства к АКБ осуществляется твердотельным реле, 
                которое управляется Windows-приложением через микроконтроллер.
            </p>
            <p>
                Windows-приложение обрабатывает данные от MCU, управляет процессом разряда и отправляет данные веб-приложению,
                используя API.
                Windows-приложение с MCU можно использовать автономно без подключения к веб-приложению, однако в данном случае 
                данные о разряде не будут сохранены.
            </p>
            <p>
                Страница <a href="~/Measurement">Измерения</a> предназначена для контроля процесса разряда в режиме реального времени.
                Все подключенные к этой странице пользователи одновременно получают актуальные данные. График разряда обновляется 
                автоматически.
            </p>
            <p>На странице <a href="~/History">История измерений</a> доступны для просмотра результаты ранее произведенных тестов.</p>
        </div>
    </div>
    <div class="border-start border-5 mt-4"">
        <div class="about_title">
            <div class="about_title_description">
                Преимущества
            </div>
        </div>
        <div class="text-start ms-3">
            <p class="mb-0">Преимущества данной системы:</p>
            <ul>
                <li>
                    <span class="fw-bold">Автоматическое управление процессом разряда.</span> 
                    Все, что Вам нужно - просто подключить аккумулятор и запустить процесс
                </li>
                <li>
                    <span class="fw-bold">Удаленный контроль процесса разряда.</span>
                    Наблюдать за процессом разряда можно с любого смартфона, планшета или ПК
                </li>
                <li>
                    <span class="fw-bold">Хранение результатов.</span>
                    Результаты предыдущих измерений хранятся в базе данных
                </li>
            </ul>
        </div>
    </div>
    <div class="border-start border-5 mt-4"">
        <div class="about_title">
            <div class="about_title_description">
                Особенности
            </div>
        </div>
        <div class="text-start ms-3">
            <p>
                В данном релизе не реализована авторизация пользователей, поэтому веб-приложение рекомендуется использовать
                в локальной сети
            </p>
        </div>
    </div>
    <div class="border-start border-5 mt-4"">
        <div class="about_title">
            <div class="about_title_description">
                В следующих релизах
            </div>
        </div>
        <div class="text-start ms-3">
            <p class="mb-0">В следующих релизах будет реализовано:</p>
            <ul>
                <li>Авторизация пользователей</li>
                <li>Возможность удалять результаты измерений для авторизованных пользователей</li>
                <li>Кнопка дистанционной аварийной остановки разряда в веб-приложении</li>
                <li>Измерение тока разряда</li>
                <li>Возможность разряда нескольких аккумуляторов одновременно</li>
                <li>Отправка сообщения об окончании разряда и результатов разряда на электронную почту</li>
                <li>Автоматическое подключение зарядного устройства сразу после окончания разряда</li>
            </ul>
        </div>
    </div>
    <div class="border-start border-5 mt-4">
        <div class="about_title">
            <div class="about_title_description">
                Фото
            </div>
        </div>
        <div class="text-start ms-3">

        </div>
    </div>
</div>

<script>
    $('.about_title').click(function(){
        $('.about_title.open').not(this).trigger('click');
        $('.about_title').not(this).parent().find('.text-start').slideUp('fast');
        $(this).parent().find('.text-start').slideToggle('fast');
        $(this).toggleClass('open');
    });

    $(function(){
        $('.text-start').slideUp(0);
    });
</script>

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Views/History/Index.cshtml
@{
    ViewData["Title"] = "История измерений";
}

<div class="text-center">
    <h3>История измерений</h3>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 col-lg-8 order-1 order-lg-0">
            <vc:measurements chart-js=ViewBag.ChartData/>
        </div>
        <div class="col-12 col-lg-4">
            <form class="mb-4 row align-items-center" asp-controller="History" asp-action="Index" method="get">
                <div class="col-12 col-xl-8">
                    <select class="form-select" name="measurementSetNumber" asp-items="ViewBag.MeasurementSetList">
                        <option selected="selected" value="0">Выберите имя теста</option>
                    </select>
                </div>
                <div class="col-12 col-xl-4 gx-xl-2 gy-2 gy-xl-0">
                    <input class="btn-sm btn-primary" type="submit" value="Получить данные" />
                </div>
            </form>

            <div>
                @{
                    if (ViewBag.MeasurementResults == null) return;
                    
                    <p>Имя теста: @ViewBag.MeasurementResults.MeasurementName</p>
                    <p>@ViewBag.MeasurementResults.MeasurementStatus</p>
                    
                    if (ViewBag.MeasurementResults.MeasurementStatus == "Батарея разряжена")
                    {
                        <p>Длительность разряда: @ViewBag.MeasurementResults.DischargeDuration.ToString(@"hh\:mm\:ss")</p>
                        <p>Измеренная емкость: @ViewBag.MeasurementResults.ResultCapacity Ач</p>
                    }
                }
            </div>
        </div>
    </div>
</div>

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Views/Measurement/Index.cshtml
@using SmartBatteryTesterWebApp.UI.Models.Chart
@model ChartJsData
@{
    ViewData["Title"] = "Измерения";
}

<div class="text-center">
    <h3>Текущие измерения</h3>
</div>

<div class="row">
    <div class="col-12 col-lg-8 order-1 order-lg-0">
        <p id="firstMessage">Начтине тест на ПК</p>
        <div id="chartContainer">
            <h5>График разряда</h5>
            <canvas id="measurementLineChart"></canvas>
        </div>
    </div>
    <div class="col-12 col-lg-4 d-flex justify-content-center mt-5">
        <span class="fw-bold" id="signalRMessage"></span>
    </div>
</div>

<script src="/js/aspnet-signalr/signalr.min.js"></script>
<script src="~/js/Chart.js/chart.umd.js"></script>

@if (Model.Labels.Count == 0)
{
    <script>
        document.getElementById('chartContainer').hidden = true;
    </script>
}

<script type="text/javascript">
    const hubConnection = new signalR.HubConnectionBuilder().withUrl('/measurementsHub').build();
    const chartElement = document.getElementById('chartContainer');
    const statusElement = document.getElementById('signalRMessage');
    const context = document.getElementById('measurementLineChart');

    let lineChart = new Chart(context, {
        type: 'line',
        data: @Json.Serialize(Model),
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
        
    function addData(chart, label, newVoltageData, newCurrentData) {
        if (`${label}` === '') {
            return;
        }

        chartElement.hidden = false;

        chart.data.labels.push(label);
        chart.data.datasets[0].data.push(newVoltageData);
        chart.data.datasets[1].data.push(newCurrentData);
        chart.update();
    }

    function changeTextColor(element) {
        element.style.color = 'red';

        setTimeout(() => {
            element.style.color = 'black';
        }, 1000);
    }

    hubConnection.on('Receive', function(message, chartData) {
        let newVoltageData = chartData.datasets[0].data[0];
        let newCurrentData = chartData.datasets[1].data[0];
        
        if (statusElement.childElementCount === 0) {
            statusElement.innerHTML = message;

        }
        else {
            statusElement.childNodes[0].nodeValue = message;
        }

        changeTextColor(statusElement);
        document.getElementById('firstMessage').hidden = true;

        addData(lineChart, chartData.labels, newVoltageData, newCurrentData);
    });

    hubConnection.start();
</script>

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Views/Shared/Components/Measurements/MeasurementsChart.cshtml
@using SmartBatteryTesterWebApp.UI.Models.Chart
@model ChartJsData

<div>
    <h5>График разряда</h5>
    <canvas id="measurementLineChart"></canvas>
</div>

<script src="~/js/Chart.js/chart.umd.min.js"></script>

<script type="text/javascript">

    let showChart = () => {
        let context = document.getElementById("measurementLineChart");
        let lineChart = new Chart(context, {
            type: 'line',
            data: @Json.Serialize(Model),
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    }

    showChart();
</script>

SmartBatteryTesterWebApp/SmartBatteryTesterWebApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Smart Battery Tester</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SmartBatteryTesterWebApp.UI.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" />
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">
</head>
<body>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="About" asp-action="Index">Smart Battery Tester</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">О проекте</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Measurement" asp-action="Index">Измерения</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">История измерений</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Smart Battery Tester / <a href="https://siarhei-v.github.io/cv/" title="Serge">Serge-V</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>